clear all;close all;
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Volumes/Xiaohui_WD/research/Postdoc/Reevaluated flux data/HiWinGS_table_long.dat
%
% Auto-generated by MATLAB on 05-Sep-2022 16:28:16

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 28);

% Specify range and delimiter
opts.DataLines = [42, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["YearMonthDay_TimeUTC", "lat_deg", "lon_deg", "CO2flux_mmol_m2_d", "kCO2660_cm_hr", "kCO2_cm_hr", "ustar_insitu_m_s", "U10n_insitu_m_s", "SST_C", "Tskin_C", "sal", "dfCO2_uatm", "sol_CO2_bulk_mole_m3_atm", "sol_CO2_skin_mole_m3_atm", "DCCO2_mmol_m3", "Sc_CO2_bulk", "U10n_ECMWF_m_s", "ustar_ECMWF_m_s", "Hs_ECMWF_tot_m", "RHw0", "MSS_ECWAM", "Hs_ECMWF_windsea_m", "Hs_ECMWF_swell_m", "MeanPeriod_ECMWF_tot_s", "MeanPeriod_ECMWF_swell_s", "MeanPeriod_ECMWF_windsea_s", "Wdir_ECMWF_deg", "Swell_dir_ECMWF_deg"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% % Specify variable properties
opts = setvaropts(opts, "lat_deg", "TrimNonNumeric", true);
opts = setvaropts(opts, "lat_deg", "ThousandsSeparator", ",");

% Import the data
HiWinGStablelong = readtable("/Volumes/Xiaohui_WD/research/Postdoc/Reevaluated flux data/ANDREXII_table_long.txt", opts);

%% Convert to output type
HiWinGStablelong = table2array(HiWinGStablelong);

%% Clear temporary variables
clear opts
%% orgnize dataset into a structure
% for i=1:28
time=datenum(HiWinGStablelong(2:end,1));%UTC
lat=str2double(HiWinGStablelong(2:end,2));
lon=str2double(HiWinGStablelong(2:end,3));
CO2flux=str2double(HiWinGStablelong(2:end,4));% eddy covariance CO2 flux, mmol/m2/d
kCO2660_cm_hr=str2double(HiWinGStablelong(2:end,5));%CO2 transfer velocity at Sc=660, cm/hr
kCO2_cm_hr=str2double(HiWinGStablelong(2:end,6));%CO2 transfer velocity at ambient Sc
ustar=str2double(HiWinGStablelong(2:end,7));%CO2 transfer velocity at ambient Sc
u10n=str2double(HiWinGStablelong(2:end,8));%m/s
SST=str2double(HiWinGStablelong(2:end,9));%bulk underway water temperature, deg C
Tskin=str2double(HiWinGStablelong(2:end,10));%skin temperature (bulk temperature corrected by COARE3.5 model cool skin effect), deg C
sal=str2double(HiWinGStablelong(2:end,11));%salinity (assumed to be 35 if missing)
dfCO2_uatm=str2double(HiWinGStablelong(2:end,12));%sea-air difference in fCO2 (=fCO2w - fCO2a), uatm
sol_CO2_bulk_mole_m3_atm=str2double(HiWinGStablelong(2:end,13));%CO2 solubility computed at bulk water temperature, moles/m3/atm
sol_CO2_skin_mole_m3_atm=str2double(HiWinGStablelong(2:end,14));%CO2 solubility computed at skin temperature, moles/m3/atm
DCCO2_mmol_m3=str2double(HiWinGStablelong(2:end,15));%sea-air difference in CO2 concentration (=sol_CO2_bulk_mole_m3_atm*fCO2w - sol_CO2_skin_mole_m3_atm*fCO2a), mmol/m3
Sc_CO2_bulk=str2double(HiWinGStablelong(2:end,16));%Schmidt number of CO2 computed at bulk water temperature
U10n_ECMWF_m_s=str2double(HiWinGStablelong(2:end,17));%10-m neutral wind speed from ECMWF model, m/s
ustar_ECMWF_m_s=str2double(HiWinGStablelong(2:end,18));%friction velocity from ECMWF model, m/s
Hs_ECMWF_tot_m=str2double(HiWinGStablelong(2:end,19));%significant wave height of total waves from ECMWF model, m
RHw0=str2double(HiWinGStablelong(2:end,20));%wave Reynolds number at 20 deg C computed from Hs_ECMWF_tot_m and ustar_insitu_m_s
MSS_ECWAM=str2double(HiWinGStablelong(2:end,21));%mean squared slope of waves from ECMWF model
Hs_ECMWF_windsea_m=str2double(HiWinGStablelong(2:end,22));%significant wave height of wind sea, m
Hs_ECMWF_swell_m=str2double(HiWinGStablelong(2:end,23));%significant wave height of swell, m
MeanPeriod_ECMWF_tot_s=str2double(HiWinGStablelong(2:end,24));%mean wave period of total waves, s
MeanPeriod_ECMWF_swell_s=str2double(HiWinGStablelong(2:end,25));%mean wave period of swell, s
MeanPeriod_ECMWF_windsea_s=str2double(HiWinGStablelong(2:end,26));%mean wave period of wind sea, s
Wdir_ECMWF_deg=str2double(HiWinGStablelong(2:end,27));%wind direction from ECMWF model, deg
Swell_dir_ECMWF_deg=str2double(HiWinGStablelong(2:end,28));%swell direction from ECMWF model, deg
% end

topo_file='ETOPO1_Bed_g_gmt4.nc';
lon_topo=ncread(topo_file,'lon');
lat_topo=ncread(topo_file,'lat');
xloc=find(lon_topo>=min(lon)-1&lon_topo<=max(lon)+1);
yloc=find(lat_topo>=min(lat)-1&lat_topo<=max(lat)+1);
count_x=length(xloc);
count_y=length(yloc);
startLoc = [xloc(1) yloc(1)]; % Start location along each coordinate
count  = [count_x count_y];
lon_topo=lon_topo(xloc);
lat_topo=lat_topo(yloc);
z=ncread(topo_file,'z',startLoc,count);
    [xx,yy]=meshgrid(lon_topo,lat_topo);
    for it=1:length(time)
    Topo(it)=interp2(xx,yy,z',lon(it),lat(it));
    end
    clear lon_topo lat_topo xx yy z
save('ANDREXII_table_long.mat')